# Generated by Django 2.1.4 on 2019-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='imagen',
        ),
        migrations.AddField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='router_specifications'),
        ),
    ]
